<a href="https://colab.research.google.com/github/2147118Joshua/Neural-Networks/blob/main/Implementation_of_Convolution_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import numpy as np
import math

In [29]:
input = np.random.randint(10,size=(5,5))
kernel = np.random.randint(0,2,(3,3))

show code

In [30]:
def convolve(input,kernel,padding,stride):
  Nout = int((((input.shape)[0]+ (2*padding) - (kernel.shape)[0])/stride)+1)
  output = np.zeros((Nout,Nout))
  x = 0
  y = 0
  size = len(output[0])
  for j in range(0,size):
    for i in range(0,size):
      submatrix = input[x:x+(kernel.shape)[0],y:y+(kernel.shape)[0]]
      output[j][i] = (np.multiply(submatrix,kernel)).sum()
      y = y + stride
    y = 0
    x = x + stride
    return output

In [31]:
padding = 0
stride = 1


Stride = 1

In [32]:
output1 = convolve(input,kernel,padding = 0 ,stride = 1)

In [33]:
output1

array([[17., 17., 28.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

Stride = 2

In [34]:
output2 = convolve(input,kernel,padding = 0 ,stride = 2)

In [35]:
output2

array([[17., 28.],
       [ 0.,  0.]])

In [36]:
def Pooling (input, filterShape, stride, poolingType):
  Nout = int((((input.shape)[0] - filterShape)/stride) + 1 )
  output = np.zeros((Nout,Nout))
  x = 0
  y = 0
  size = len(output[0])
  for j in range(0,size):
    for i in range(0,size):
      submatrix = input[x:x + filterShape, y:y + filterShape]
      if poolingType == 'max':
        output[j][i] = submatrix.max()
      elif poolingType == 'average':
        output[j][i] = np.average(submatrix)
      else : # sum
        output[j][i] = submatrix.sum()
      y = y + stride
    y = 0
    x = x + stride
  return output

In [37]:
sumPooled = Pooling(output1,2,1,'sum')
print("Sum Pooling : \n",sumPooled)

Sum Pooling : 
 [[34. 45.]
 [ 0.  0.]]


In [38]:
avgPooled = Pooling(output1,2,1,'average')
print("Average Pooling : \n",avgPooled)

Average Pooling : 
 [[ 8.5  11.25]
 [ 0.    0.  ]]


In [39]:
maxPooled = Pooling(output1,2,1,'max')
print("Max Pooling : \n",maxPooled)

Max Pooling : 
 [[17. 28.]
 [ 0.  0.]]


In [40]:
sumPooledFlattened = sumPooled.flatten()
print("Flattened version of sum pooled : ",sumPooledFlattened)

Flattened version of sum pooled :  [34. 45.  0.  0.]


In [41]:
avgPooledFlattened = avgPooled.flatten()
print("Flattened version of average pooled : ",avgPooledFlattened)

Flattened version of average pooled :  [ 8.5  11.25  0.    0.  ]


In [42]:
maxPooledFlattened = maxPooled.flatten()
print("Flattened version of max pooled : ",maxPooledFlattened)

Flattened version of max pooled :  [17. 28.  0.  0.]


In [43]:
X = []
(X.append(maxPooledFlattened[0:]))
T = np.array([[1]])
W1 = np.random.uniform(size=(1,4),low=-0.5,high = 0.8)
W2 = (np.random.uniform(size=(1,2),low=-0.5,high = 0.8))[0]
B1 = np.array([1,1])
B2 = np.array([0.5])
alpha = 0.1
epoch = 200
error_tolerence = 0.40

In [44]:
def BipolarSigmoid(x):
  return (2/(1+math.exp(-x))) - 1

In [45]:
def BipolarSigmoidDerivative(x):
  return 0.5*(1-x)*(1+x)

In [46]:
def DeltaHidden(delta_in, Z):
  return delta_in * BipolarSigmoidDerivative(Z)

In [47]:
def Perceptron(x,w1,w2,b1,b2,t,a,e):
  for count in range(e):
    for i,row in enumerate(x):
      Zin = np.dot(row, w1.T) + b1
      Zout = np.vectorize(BipolarSigmoid)(Zin)
      Yin = np.dot(Zout,w2.transpose()) + b2
      Y = np.vectorize(BipolarSigmoid)(Yin)
      if(t[i] != Y[0]):
        delta_y = (t[i] - Y) * (BipolarSigmoidDerivative(Y))
        delta_in_z = delta_y * w2
        delta_Z = delta_in_z * np.vectorize(BipolarSigmoidDerivative)(Zout)
        for index in range(len(w1)):
          w1[index] = (w1[index].T + a*delta_Z[index]*row.T).T
        w2 = (w2.T +a*delta_y*Zout.T).T
        b1 = b1 + a*delta_Z
        b2 = b2 + a*delta_y
  return GetResult(w1,w2,b1,b2)




def GetResult(w1,w2,b1,b2):
  result = []
  result.append(w1)
  result.append(w2)
  result.append(b1)
  result.append(b2)
  return result

epoch = 1
adjustedWeights = Perceptron(X,W1,W2,B1,B2,T,alpha,epoch)
W1 = adjustedWeights[0]
W2 = adjustedWeights[1]
B1 = adjustedWeights[2]
B2 = adjustedWeights[3]

print("W1 : ",W1)
print("W2 : ",W2)
print("B1 : ",B1)
print("B2 : ",B2)


W1 :  [[0.42360711 0.02146188 0.63910217 0.30139494]]
W2 :  [-0.05004073  0.06608007]
B1 :  [0.99999902 1.00000032]
B2 :  [0.53729153]
